//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace FoxySharp.DataFeed {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class custom_field {
        
        private string custom_field_nameField;
        
        private string custom_field_valueField;
        
        private sbyte custom_field_is_hiddenField;
        
        /// <remarks/>
        public string custom_field_name {
            get {
                return this.custom_field_nameField;
            }
            set {
                this.custom_field_nameField = value;
            }
        }
        
        /// <remarks/>
        public string custom_field_value {
            get {
                return this.custom_field_valueField;
            }
            set {
                this.custom_field_valueField = value;
            }
        }
        
        /// <remarks/>
        public sbyte custom_field_is_hidden {
            get {
                return this.custom_field_is_hiddenField;
            }
            set {
                this.custom_field_is_hiddenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transaction_detail_option {
        
        private string product_option_nameField;
        
        private string product_option_valueField;
        
        private float price_modField;
        
        private float weight_modField;
        
        /// <remarks/>
        public string product_option_name {
            get {
                return this.product_option_nameField;
            }
            set {
                this.product_option_nameField = value;
            }
        }
        
        /// <remarks/>
        public string product_option_value {
            get {
                return this.product_option_valueField;
            }
            set {
                this.product_option_valueField = value;
            }
        }
        
        /// <remarks/>
        public float price_mod {
            get {
                return this.price_modField;
            }
            set {
                this.price_modField = value;
            }
        }
        
        /// <remarks/>
        public float weight_mod {
            get {
                return this.weight_modField;
            }
            set {
                this.weight_modField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transaction_detail_options {
        
        private transaction_detail_option[] transaction_detail_optionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction_detail_option")]
        public transaction_detail_option[] transaction_detail_option {
            get {
                return this.transaction_detail_optionField;
            }
            set {
                this.transaction_detail_optionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transaction_detail {
        
        private string product_nameField;
        
        private float product_priceField;
        
        private sbyte product_quantityField;
        
        private float product_weightField;
        
        private string product_codeField;
        
        private string parent_codeField;
        
        private string imageField;
        
        private string urlField;
        
        private string lengthField;
        
        private string widthField;
        
        private string heightField;
        
        private string expiresField;
        
        private string sub_token_urlField;
        
        private string subscription_frequencyField;
        
        private string subscription_startdateField;
        
        private string subscription_nextdateField;
        
        private string subscription_enddateField;
        
        private sbyte is_future_line_itemField;
        
        private string shiptoField;
        
        private string category_descriptionField;
        
        private string category_codeField;
        
        private string product_delivery_typeField;
        
        private transaction_detail_option[] transaction_detail_optionsField;
        
        /// <remarks/>
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                this.product_nameField = value;
            }
        }
        
        /// <remarks/>
        public float product_price {
            get {
                return this.product_priceField;
            }
            set {
                this.product_priceField = value;
            }
        }
        
        /// <remarks/>
        public sbyte product_quantity {
            get {
                return this.product_quantityField;
            }
            set {
                this.product_quantityField = value;
            }
        }
        
        /// <remarks/>
        public float product_weight {
            get {
                return this.product_weightField;
            }
            set {
                this.product_weightField = value;
            }
        }
        
        /// <remarks/>
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                this.product_codeField = value;
            }
        }
        
        /// <remarks/>
        public string parent_code {
            get {
                return this.parent_codeField;
            }
            set {
                this.parent_codeField = value;
            }
        }
        
        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public string length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public string expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
            }
        }
        
        /// <remarks/>
        public string sub_token_url {
            get {
                return this.sub_token_urlField;
            }
            set {
                this.sub_token_urlField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_frequency {
            get {
                return this.subscription_frequencyField;
            }
            set {
                this.subscription_frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_startdate {
            get {
                return this.subscription_startdateField;
            }
            set {
                this.subscription_startdateField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_nextdate {
            get {
                return this.subscription_nextdateField;
            }
            set {
                this.subscription_nextdateField = value;
            }
        }
        
        /// <remarks/>
        public string subscription_enddate {
            get {
                return this.subscription_enddateField;
            }
            set {
                this.subscription_enddateField = value;
            }
        }
        
        /// <remarks/>
        public sbyte is_future_line_item {
            get {
                return this.is_future_line_itemField;
            }
            set {
                this.is_future_line_itemField = value;
            }
        }
        
        /// <remarks/>
        public string shipto {
            get {
                return this.shiptoField;
            }
            set {
                this.shiptoField = value;
            }
        }
        
        /// <remarks/>
        public string category_description {
            get {
                return this.category_descriptionField;
            }
            set {
                this.category_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string category_code {
            get {
                return this.category_codeField;
            }
            set {
                this.category_codeField = value;
            }
        }
        
        /// <remarks/>
        public string product_delivery_type {
            get {
                return this.product_delivery_typeField;
            }
            set {
                this.product_delivery_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction_detail_option", IsNullable=false)]
        public transaction_detail_option[] transaction_detail_options {
            get {
                return this.transaction_detail_optionsField;
            }
            set {
                this.transaction_detail_optionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class custom_fields {
        
        private custom_field[] custom_fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("custom_field")]
        public custom_field[] custom_field {
            get {
                return this.custom_fieldField;
            }
            set {
                this.custom_fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transaction_details {
        
        private transaction_detail[] transaction_detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction_detail")]
        public transaction_detail[] transaction_detail {
            get {
                return this.transaction_detailField;
            }
            set {
                this.transaction_detailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transaction {
        
        private int idField;
        
        private sbyte store_idField;
        
        private string store_versionField;
        
        private sbyte is_testField;
        
        private sbyte is_hiddenField;
        
        private sbyte data_is_fedField;
        
        private string transaction_dateField;
        
        private string processor_responseField;
        
        private short customer_idField;
        
        private sbyte is_anonymousField;
        
        private sbyte minfraud_scoreField;
        
        private string customer_first_nameField;
        
        private string customer_last_nameField;
        
        private string customer_companyField;
        
        private string customer_address1Field;
        
        private string customer_address2Field;
        
        private string customer_cityField;
        
        private string customer_stateField;
        
        private int customer_postal_codeField;
        
        private string customer_countryField;
        
        private string customer_phoneField;
        
        private string customer_emailField;
        
        private string customer_ipField;
        
        private string shipping_first_nameField;
        
        private string shipping_last_nameField;
        
        private string shipping_companyField;
        
        private string shipping_address1Field;
        
        private string shipping_address2Field;
        
        private string shipping_cityField;
        
        private string shipping_stateField;
        
        private string shipping_postal_codeField;
        
        private string shipping_countryField;
        
        private string shipping_phoneField;
        
        private string shipto_shipping_service_descriptionField;
        
        private string purchase_orderField;
        
        private string cc_number_maskedField;
        
        private string cc_typeField;
        
        private sbyte cc_exp_monthField;
        
        private short cc_exp_yearField;
        
        private sbyte cc_start_date_monthField;
        
        private short cc_start_date_yearField;
        
        private sbyte cc_issue_numberField;
        
        private float product_totalField;
        
        private sbyte tax_totalField;
        
        private float shipping_totalField;
        
        private float order_totalField;
        
        private string payment_gateway_typeField;
        
        private string receipt_urlField;
        
        private string taxesField;
        
        private string discountsField;
        
        private string attributesField;
        
        private string statusField;
        
        private string customer_passwordField;
        
        private string customer_password_saltField;
        
        private string customer_password_hash_typeField;
        
        private sbyte customer_password_hash_configField;
        
        private custom_field[] custom_fieldsField;
        
        private transaction_detail[] transaction_detailsField;
        
        private string shipto_addressesField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public sbyte store_id {
            get {
                return this.store_idField;
            }
            set {
                this.store_idField = value;
            }
        }
        
        /// <remarks/>
        public string store_version {
            get {
                return this.store_versionField;
            }
            set {
                this.store_versionField = value;
            }
        }
        
        /// <remarks/>
        public sbyte is_test {
            get {
                return this.is_testField;
            }
            set {
                this.is_testField = value;
            }
        }
        
        /// <remarks/>
        public sbyte is_hidden {
            get {
                return this.is_hiddenField;
            }
            set {
                this.is_hiddenField = value;
            }
        }
        
        /// <remarks/>
        public sbyte data_is_fed {
            get {
                return this.data_is_fedField;
            }
            set {
                this.data_is_fedField = value;
            }
        }
        
        /// <remarks/>
        public string transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                this.transaction_dateField = value;
            }
        }
        
        /// <remarks/>
        public string processor_response {
            get {
                return this.processor_responseField;
            }
            set {
                this.processor_responseField = value;
            }
        }
        
        /// <remarks/>
        public short customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public sbyte is_anonymous {
            get {
                return this.is_anonymousField;
            }
            set {
                this.is_anonymousField = value;
            }
        }
        
        /// <remarks/>
        public sbyte minfraud_score {
            get {
                return this.minfraud_scoreField;
            }
            set {
                this.minfraud_scoreField = value;
            }
        }
        
        /// <remarks/>
        public string customer_first_name {
            get {
                return this.customer_first_nameField;
            }
            set {
                this.customer_first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string customer_last_name {
            get {
                return this.customer_last_nameField;
            }
            set {
                this.customer_last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string customer_company {
            get {
                return this.customer_companyField;
            }
            set {
                this.customer_companyField = value;
            }
        }
        
        /// <remarks/>
        public string customer_address1 {
            get {
                return this.customer_address1Field;
            }
            set {
                this.customer_address1Field = value;
            }
        }
        
        /// <remarks/>
        public string customer_address2 {
            get {
                return this.customer_address2Field;
            }
            set {
                this.customer_address2Field = value;
            }
        }
        
        /// <remarks/>
        public string customer_city {
            get {
                return this.customer_cityField;
            }
            set {
                this.customer_cityField = value;
            }
        }
        
        /// <remarks/>
        public string customer_state {
            get {
                return this.customer_stateField;
            }
            set {
                this.customer_stateField = value;
            }
        }
        
        /// <remarks/>
        public int customer_postal_code {
            get {
                return this.customer_postal_codeField;
            }
            set {
                this.customer_postal_codeField = value;
            }
        }
        
        /// <remarks/>
        public string customer_country {
            get {
                return this.customer_countryField;
            }
            set {
                this.customer_countryField = value;
            }
        }
        
        /// <remarks/>
        public string customer_phone {
            get {
                return this.customer_phoneField;
            }
            set {
                this.customer_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string customer_email {
            get {
                return this.customer_emailField;
            }
            set {
                this.customer_emailField = value;
            }
        }
        
        /// <remarks/>
        public string customer_ip {
            get {
                return this.customer_ipField;
            }
            set {
                this.customer_ipField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_first_name {
            get {
                return this.shipping_first_nameField;
            }
            set {
                this.shipping_first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_last_name {
            get {
                return this.shipping_last_nameField;
            }
            set {
                this.shipping_last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_company {
            get {
                return this.shipping_companyField;
            }
            set {
                this.shipping_companyField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_address1 {
            get {
                return this.shipping_address1Field;
            }
            set {
                this.shipping_address1Field = value;
            }
        }
        
        /// <remarks/>
        public string shipping_address2 {
            get {
                return this.shipping_address2Field;
            }
            set {
                this.shipping_address2Field = value;
            }
        }
        
        /// <remarks/>
        public string shipping_city {
            get {
                return this.shipping_cityField;
            }
            set {
                this.shipping_cityField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_state {
            get {
                return this.shipping_stateField;
            }
            set {
                this.shipping_stateField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_postal_code {
            get {
                return this.shipping_postal_codeField;
            }
            set {
                this.shipping_postal_codeField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_country {
            get {
                return this.shipping_countryField;
            }
            set {
                this.shipping_countryField = value;
            }
        }
        
        /// <remarks/>
        public string shipping_phone {
            get {
                return this.shipping_phoneField;
            }
            set {
                this.shipping_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string shipto_shipping_service_description {
            get {
                return this.shipto_shipping_service_descriptionField;
            }
            set {
                this.shipto_shipping_service_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string purchase_order {
            get {
                return this.purchase_orderField;
            }
            set {
                this.purchase_orderField = value;
            }
        }
        
        /// <remarks/>
        public string cc_number_masked {
            get {
                return this.cc_number_maskedField;
            }
            set {
                this.cc_number_maskedField = value;
            }
        }
        
        /// <remarks/>
        public string cc_type {
            get {
                return this.cc_typeField;
            }
            set {
                this.cc_typeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte cc_exp_month {
            get {
                return this.cc_exp_monthField;
            }
            set {
                this.cc_exp_monthField = value;
            }
        }
        
        /// <remarks/>
        public short cc_exp_year {
            get {
                return this.cc_exp_yearField;
            }
            set {
                this.cc_exp_yearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte cc_start_date_month {
            get {
                return this.cc_start_date_monthField;
            }
            set {
                this.cc_start_date_monthField = value;
            }
        }
        
        /// <remarks/>
        public short cc_start_date_year {
            get {
                return this.cc_start_date_yearField;
            }
            set {
                this.cc_start_date_yearField = value;
            }
        }
        
        /// <remarks/>
        public sbyte cc_issue_number {
            get {
                return this.cc_issue_numberField;
            }
            set {
                this.cc_issue_numberField = value;
            }
        }
        
        /// <remarks/>
        public float product_total {
            get {
                return this.product_totalField;
            }
            set {
                this.product_totalField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tax_total {
            get {
                return this.tax_totalField;
            }
            set {
                this.tax_totalField = value;
            }
        }
        
        /// <remarks/>
        public float shipping_total {
            get {
                return this.shipping_totalField;
            }
            set {
                this.shipping_totalField = value;
            }
        }
        
        /// <remarks/>
        public float order_total {
            get {
                return this.order_totalField;
            }
            set {
                this.order_totalField = value;
            }
        }
        
        /// <remarks/>
        public string payment_gateway_type {
            get {
                return this.payment_gateway_typeField;
            }
            set {
                this.payment_gateway_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string receipt_url {
            get {
                return this.receipt_urlField;
            }
            set {
                this.receipt_urlField = value;
            }
        }
        
        /// <remarks/>
        public string taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        /// <remarks/>
        public string discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
            }
        }
        
        /// <remarks/>
        public string attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string customer_password {
            get {
                return this.customer_passwordField;
            }
            set {
                this.customer_passwordField = value;
            }
        }
        
        /// <remarks/>
        public string customer_password_salt {
            get {
                return this.customer_password_saltField;
            }
            set {
                this.customer_password_saltField = value;
            }
        }
        
        /// <remarks/>
        public string customer_password_hash_type {
            get {
                return this.customer_password_hash_typeField;
            }
            set {
                this.customer_password_hash_typeField = value;
            }
        }
        
        /// <remarks/>
        public sbyte customer_password_hash_config {
            get {
                return this.customer_password_hash_configField;
            }
            set {
                this.customer_password_hash_configField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("custom_field", IsNullable=false)]
        public custom_field[] custom_fields {
            get {
                return this.custom_fieldsField;
            }
            set {
                this.custom_fieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction_detail", IsNullable=false)]
        public transaction_detail[] transaction_details {
            get {
                return this.transaction_detailsField;
            }
            set {
                this.transaction_detailsField = value;
            }
        }
        
        /// <remarks/>
        public string shipto_addresses {
            get {
                return this.shipto_addressesField;
            }
            set {
                this.shipto_addressesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class transactions {
        
        private transaction[] transactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction")]
        public transaction[] transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class foxydata {
        
        private transaction[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction", IsNullable=false)]
        public transaction[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
            }
        }
    }
}
